apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: lockss
  name: lockss-rw-networkpolicies-role
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete", "deletecollection"]
