#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# deploy-lockss - Collect host system information needed to run a LOCKSS stack
#
# Copyright (c) 2000-2019, Board of Trustees of Leland Stanford Jr. University
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
# may be used to endorse or promote products derived from this software without
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# Usage: deploy-lockss [-h|--help]

# Revision history:
# 2019-04-18 version 1
# ---------------------------------------------------------------------------
PROGNAME=${0##*/}
VERSION="1.0"

##
## Relative paths
##

_0=$(basename "${0}")
_D0=$(dirname "${0}")

##
## Load _util
##

. "${_D0}/_util"

##
## Definitions
##

# Files
set -a
. "${CONFIG_DIR}/system.cfg"
set +a

#Data
declare -a deploy_service_names
declare -a svcs
declare -A svc_port_map
STACK_PREFIX="lockss-stack"
KUBECTL="microk8s kubectl -n lockss"

clean_up() { # Perform pre-exit housekeeping
  log_script_exit  "${PROGNAME}"
}

error_exit() {
  logger_fatal "${1:-"Unknown Error"}" >&2
  clean_up
  exit 1
}

graceful_exit() {
  clean_up
  exit
}

signal_exit() { # Handle trapped signals
  case $1 in
  INT)
    logger_info "Program interrupted by user"
    ;;
  TERM)
    logger_error "Program terminated"
    graceful_exit
    ;;
  *)
    error_exit "Terminating on unknown signal"
    ;;
  esac
}

usage() {
  echo -e "Usage: $PROGNAME [-h|--help] [-w|--wait] [-a|--args ARGS_ADDITIONAL]"
}

help_message() {
  cat <<-_EOF_
  $PROGNAME ver. $VERSION
  Deploy the lockss stacks to docker.

  $(usage)

  Options:
  -h, --help  Display this help message and exit.
  -w, --wait Use a wait file to signal stack ready.
  -a, --args ARGS_ADDITIONAL  Add additional runtime options.
    Where 'ARGS_ADDITIONAL' is the additional arguments.

_EOF_
  return
}

#initialize the service arrays based on system.cfg info.
init_service_arrays() {
  if ${USE_LOCKSS_CFG}; then
    svcs+=("cfg")
    deploy_service_names+=("lockss-configuration-service")
    svc_port_map["lockss-configuration-service"]="$CFG_UI_PORT:$CFG_DEFAULT_UI_PORT $CFG_REST_PORT:$CFG_DEFAULT_REST_PORT"
  fi
  if ${USE_LOCKSS_MDQ}; then
    svcs+=("mdq")
    deploy_service_names+=("lockss-metadata-service")
    svc_port_map["lockss-metadata-service"]="$MDQ_UI_PORT:$MDQ_DEFAULT_UI_PORT $MDQ_REST_PORT:$MDQ_DEFAULT_REST_PORT"
  fi
  if ${USE_LOCKSS_MDX}; then
    svcs+=("mdx")
    deploy_service_names+=("lockss-metadata-extraction-service")
    svc_port_map["lockss-metadata-extraction-service"]="$MDX_UI_PORT:$MDX_DEFAULT_UI_PORT $MDX_REST_PORT:$MDX_DEFAULT_REST_PORT"
  fi
  if ${USE_LOCKSS_POL}; then
    svcs+=("pol")
    deploy_service_names+=("lockss-poller-service")
    svc_port_map["lockss-poller-service"]="$POL_UI_PORT:$POL_DEFAULT_UI_PORT $POL_REST_PORT:$POL_DEFAULT_REST_PORT"
  fi
  if ${USE_LOCKSS_REPO}; then
    svcs+=("repo")
    deploy_service_names+=("lockss-repository-service")
    svc_port_map["lockss-repository-service"]="$REPO_REST_PORT:$REPO_DEFAULT_REST_PORT"
  fi
  if ${USE_LOCKSS_POSTGRES}; then
    svcs+=("postgres")
    deploy_service_names+=("lockss-postgres-service")
    svc_port_map["lockss-postgres-service"]="$POSTGRES_PORT:$POSTGRES_DEFAULT_PORT"
  fi
  if ${USE_LOCKSS_SOLR}; then
    svcs+=("solr")
    deploy_service_names+=("lockss-solr-service")
    svc_port_map["lockss-solr-service"]="$SOLR_PORT:$SOLR_DEFAULT_PORT"
  fi
  if ${USE_LOCKSS_HDFS}; then
    svcs+=("hdfs")
    deploy_service_names+=("lockss-hdfs-service")
  fi
  if ${USE_LOCKSS_PYWB}; then
    svcs+=("pywb")
    deploy_service_names+=("lockss-pywb-service")
    svc_port_map["lockss-pywb-service"]="$PYWB_PORT:$PYWB_DEFAULT_PORT"
  fi
  if ${USE_LOCKSS_OPENWB}; then
    svcs+=("openwayback")
    deploy_service_names+=("lockss-openwayback-service")
    svc_port_map["lockss-openwayback-service"]="$OPENWB_PORT:$OPENWB_DEFAULT_PORT"
  fi
}

# Check our secrets
check_installed_secrets() {
  logger_info "checking installed secrets..."
  Check_Secret 'lockss-postgres-pass'
  Check_Secret 'lockss-ui-pass'
  Check_Secret 'lockss-auth'
  Check_Secret 'solr-auth'
}

check_installed_volumes() {
  local stack=$1
  local wait_file
  # Check the mountpoints
  for svc in "${svcs[@]}"; do
    logger_debug "clearing  wait file in ${LOCKSS_DATA_DIR}/$stack-${svc}-data"
    wait_file="${LOCKSS_DATA_DIR}/$stack-${svc}-data/${LOCKSS_WAIT_FILE}"
    if [ -f $wait_file ]; then
      rm "${LOCKSS_DATA_DIR}/$stack-${svc}-data/${LOCKSS_WAIT_FILE}" >/dev/null ||
        logger_warn "Unable to delete file $wait_file"
    fi
  done
}


wait_for_ready() {
  local wait_for_file=$1
  logger_info "Waiting for pods to be marked 'Ready'..."
  $KUBECTL wait --for=condition=Ready --all pods --timeout=90s | logger_info
  if [ "${CHECK_WAIT_FILE}" = "TRUE" ]; then
    logger_info "waiting for LOCKSS wait file..."
    while [ ! -f $wait_for_file ]
    do
      sleep 2
    done
    logger_info "LOCKSS services are now ready for use."
  fi
}

# Deploy the stack with incoming stack num
deploy_stack() {
  local stack=${STACK_PREFIX}$1
  # Source config.info and env.sh
  set -a
  . "${DOCKER_CONFIGS_DIR}/$stack/env.sh"
  set +a
  check_installed_volumes $stack
  pushd . &>/dev/null
  logger_info "Deploying services and deployments for stack $stack"
  for svc in "${deploy_service_names[@]}"; do
    logger_trace "Deploying service from ${svc}..."
    $KUBECTL apply -f "${DOCKER_CONFIGS_DIR}/$stack/svcs/${svc}.yaml" | logger_debug
#    $KUBECTL expose deployment $svc
  done
  wait_for_ready "${LOCKSS_DATA_DIR}/$stack-pol-data/${LOCKSS_WAIT_FILE}"
  popd &>/dev/null
}

##
## MAIN
##
# Trap signals
trap "signal_exit TERM" TERM HUP
trap "signal_exit INT" INT
#init the logger and mark script entry
logger_init
log_script_entry "${PROGNAME}"
umask 002

STACK_DIRS=(${DOCKER_CONFIGS_DIR}/*/)
NUM_STACKS=${#STACK_DIRS[@]}
STACK_NUM=0
ARGS_ADDITIONAL=""
# Parse command-line
while [[ -n $1 ]]; do
  case $1 in
  -h | --help)
    help_message
    graceful_exit
    ;;
  -a | --args)
    shift
    export ARGS_ADDITIONAL="$1"
    logger_debug "Adding additional runtime args $ARGS_ADDITIONAL"
    shift
    ;;
  -w | --wait)
    CHECK_WAIT_FILE="TRUE"
    logger_debug "Using wait file to check ready"
    shift
    ;;
  [1-9])
    STACK_NUM=$1
    ;;
  -* | --*)
    usage
    error_exit "Unknown option $1"
    ;;
  *)
    logger_trace "Argument $1 to process..."
    ;;
  esac
  shift
done
# Sanity checks
logger_info "Checking system..."

if $(am_i_root); then
  error_exit "This script should not be run as root. Run as the lockss user."
fi
Check_Runnable

init_service_arrays

if [ ${NUM_STACKS} -eq 0 ]; then
  error_exit "Unable to find generated stack info, run configure, generate and install first."
elif [ ${NUM_STACKS} -eq 1 ]; then
  deploy_stack ""
elif [ ${STACK_NUM} -eq 0 ]; then
  logger_info "Deploying ${NUM_STACKS} stacks found in ${DOCKER_CONFIGS_DIR}"
  deploy_stack ""
  for ((num = 1; num < $NUM_STACKS; num++)); do
    deploy_stack $num
  done
elif [ -e "${DOCKER_CONFIGS_DIR}/${STACK_PREFIX}${STACK_NUM}" ]; then
  deploy_stack ${STACK_NUM}
else
  error_exit "Unable to find generated stack info for ${STACK_NUM}"
fi

graceful_exit
