#!/bin/sh

# Copyright (c) 2000-2018, Board of Trustees of Leland Stanford Jr. University
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
# may be used to endorse or promote products derived from this software without
# specific prior written permission. 
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

##
## Relative paths
##

_0=$(basename "${0}")
_D0=$(dirname "${0}")

##
## Load _util
##

. "${_D0}/_util"

##
## Definitions
##

# Directories
CONFIG_DIR="${_D0}/../config"

# Files
DOCKER_COMPOSE_FILE="${_D0}/../docker-compose.yaml"
DOCKER_COMPOSE_PROPS_FILE="${_D0}/../docker-compose.props.yaml"

# Other
PROPS_URL=''

##
## function Print_Usage
##

Print_Usage()
{
  cat <<END_OF_STRING
Usage: ${_0} [--props-url=U]
       ${_0} [--help]

  --help, -help, -h                  Print this message and exit
  --props-url=U, -props-url U, -p U  Use remote props URL U
END_OF_STRING
}

##
## MAIN
##

# Source conf.docker.sh and conf.sh 
set -a
. "${CONFIG_DIR}/conf/conf.sh"
set +a

# Option parsing loop
while true ; do
  case "${1}" in
    -h|-help|--help)
      Print_Usage
      exit 0 ;;
    -p|-props-url)
      PROPS_URL="${2}"
      shift ; shift ; continue ;;
    --props-url=*)
      PROPS_URL=$(Get_Value "${1}")
      shift ; continue ;;
    --)
      shift ;;
  esac
  break
done

# Sanity checks
Check_Installed 'docker' 'docker-compose'
Check_Docker

# Props URL
URL=''
DOCKER_COMPOSE_FLAGS="--file=${DOCKER_COMPOSE_FILE}"
if [ "X${PROPS_URL}" = "X" ]; then
  URL="http://${PROPS_HOST}:${PROPS_PORT}/lockss.xml"
  DOCKER_COMPOSE_FLAGS="${DOCKER_COMPOSE_FLAGS} --file=${DOCKER_COMPOSE_PROPS_FILE}"  
else
  URL="${PROPS_URL}"
fi
CFG_CMD="-l ${URL} ${CFG_CMD}"

# Docker-Compose
docker-compose $DOCKER_COMPOSE_FLAGS "$@"
