#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# stop-lockss - Stop LOCKSS stack and containers.

# Copyright (c) 2000-2023, Board of Trustees of Leland Stanford Jr. University
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
# may be used to endorse or promote products derived from this software without
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# Usage: stop-lockss [-h|--help]
#
# Revision history:
# 2019-04-18 version 1
# ---------------------------------------------------------------------------
PROGNAME=${0##*/}
VERSION="1.0"

_0=$(basename "${0}")
_D0=$(dirname "${0}")

##
## Load _util
##

. "${_D0}/_util" || { echo "${0##*/}: failed to load _util" >&2; exit 1; }


declare -a secrets=("lockss-ui-pass" "lockss-auth" "lockss-postgres-pass")
declare -a SERVICES
declare -A -r SERVICE_NAMES=(
 [cfg]="lockss-configuration-service"
 [md]="lockss-metadata-service"
 [pol]="lockss-poller-service"
 [crawl]="lockss-crawler-service"
 [soap]="lockss-soap-service"
 [repo]="lockss-repository-service"
 [postgres]="lockss-postgres-service"
 [solr]="lockss-solr-service"
 [hdfs]="lockss-hdfs-service"
 [pywb]="lockss-pywb-service"
 [openwb]="lockss-openwayback-service"
)
STACK_PREFIX="lockss-stack"

clean_up() { # Perform pre-exit housekeeping
  log_script_exit  "${PROGNAME}"
}

logger_error_exit() {
  logger_error "${1:-"Unknown Error"}"
  clean_up
  exit 1
}

graceful_exit() {
  clean_up
  exit
}

signal_exit() { # Handle trapped signals
  case $1 in
  INT)
    logger_error_exit "Program interrupted by user"
    ;;
  TERM)
    logger_error "Program terminated"
    graceful_exit
    ;;
  *)
    logger_error_exit "Terminating on unknown signal"
    ;;
  esac
}

usage() {
  cat <<- _EOF_
Usage:

  $PROGNAME [-s|--services SVCS]

  $PROGNAME [-h|--help]
_EOF_
}

help_message() {
  cat <<-_EOF_
$PROGNAME version $VERSION
Stop the LOCKSS stack.

$(usage)

Options:

  -h, --help           Display this help message and exit.
  -s, --services SVCS  Stop only service in SVCS (semicolon-separated).

_EOF_
  return
}

undeploy_stack() {
  local stack=${STACK_PREFIX}$1
  # Source env.sh
  source_env "${stack}"
  logger_info "Undeploying stack $stack"
  svc_arr=()
  # if no services req get all running services and stop them.
  if [ -z "$REQ_SERVICES" ]; then
    logger_info "Stopping all running services."
    services=$(kubectl_lockss get svc -o jsonpath='{.items[*].metadata.name}')
    IFS=' ' read -a svc_arr <<< "$services"
  else
    logger_info "Stopping only requested services."
    for svc in "${SERVICES[@]}"; do
      svc_arr+=(${SERVICE_NAMES[$svc]})
    done
  fi
  # loop through the service array stop everything for that service
	for svc in "${svc_arr[@]}"
	do
    logger_debug "Stopping service ${svc}..."
    # this should delete the deployment, replicaset, pod
    kubectl_lockss delete deployment -l lockss-stack-id=${stack} -l io.kompose.service=${svc} | logger_debug
    kubectl_lockss delete service -l lockss-stack-id=${stack} -l io.kompose.service=${svc} | logger_debug
  done
	for svc in "${svc_arr[@]}"
	do
    podname=$(kubectl_lockss get pod -l lockss-stack-id=${stack} 2> /dev/null | grep "${svc}" )
    logger_debug "Waiting for pod $podname to exit."
    if [ -n "${podname}" ]; then
      kubectl_lockss wait --for=delete -l lockss-stack-id=${stack} pod ${podname} --timeout=60s 2>&1 | logger_debug
    fi
  done

  # Delete Kubernetes CronJobs
  cronjobs_arr=()
  cronjobs=$(kubectl_lockss get cronjob -o jsonpath='{.items[*].metadata.name}')
  IFS=' ' read -a cronjobs_arr <<< "$cronjobs"
	for cronjob_name in "${cronjobs_arr[@]}"
	do
    kubectl_lockss delete cronjob "${cronjob_name}" | logger_debug
  done
  logger_info "Pod shutdown complete"
}

##
## MAIN
##

# Special case without logging
if [ $# -eq 1 ] && [ "$1" = '-h' -o "$1" = '--help' ]; then
  help_message
  exit 0
fi

# Trap signals
trap "signal_exit TERM" TERM HUP
trap "signal_exit INT" INT

# Source system config file
source_config
logger_init

log_script_entry "${PROGNAME}"
umask 002

STACK_NUM=0

# Parse command-line
while [[ -n $1 ]]; do
  case $1 in
  [1-9])
    STACK_NUM=$1
    ;;
  -s | --services)
    export REQ_SERVICES="$2"
    logger_debug "Adding list of service to assemble $REQ_SERVICES"
    shift; shift
    ;;
  -*)
    usage
    logger_error_exit "Unknown option $1"
    ;;
  *)
    logger_debug "Argument $1 to process..."
    ;;
  esac
  shift
done


# Sanity checks
Check_Runnable
Check_Configured
init_service_arrays

if [[ ${STACK_NUM} -eq 0 ]]; then
  undeploy_stack ""
else
  undeploy_stack ${STACK_NUM}
fi
echo "========================================="
number_of_services=$(kubectl_lockss get svc 2> /dev/null | wc -l)
if ((number_of_services > 0)); then
  echo "These LOCKSS services are now running."
  kubectl_lockss get deployments --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}'
else
    kubectl_lockss delete NetworkPolicy lockss-network-policy-admin-access 2> /dev/null | logger_debug
    kubectl_lockss delete NetworkPolicy lockss-network-policy-content-access 2> /dev/null | logger_debug
    echo "All LOCKSS services are stopped."
fi
echo "========================================="
graceful_exit
