#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# uninstall-lockss - Undeploy all stacks and remove all installed stack info..

# Copyright (c) 2000-2023, Board of Trustees of Leland Stanford Jr. University
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
# may be used to endorse or promote products derived from this software without
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# Usage: uninstall-lockss [-h|--help]
#
# Revision history:
# 2019-04-18 version 1
# ---------------------------------------------------------------------------
PROGNAME=${0##*/}
VERSION="1.0"

##
## Relative paths
##

_0=$(basename "${0}")
_D0=$(dirname "${0}")

##
## Load _util
##

. "${_D0}/_util"
# Source system config file
set -a
. "${CONFIG_DIR}/system.cfg"
set +a

clean_up() { # Perform pre-exit housekeeping
  log_script_exit  "${PROGNAME}"
}

logger_error_exit() {
  logger_error "${1:-"Unknown Error"}"
  clean_up
  exit 1
}

graceful_exit() {
  clean_up
  exit
}

signal_exit() { # Handle trapped signals
  case $1 in
  INT)
    logger_error_exit "Program interrupted by user"
    ;;
  TERM)
    logger_error "Program terminated"
    graceful_exit
    ;;
  *)
    logger_error_exit "Terminating on unknown signal"
    ;;
  esac
}

usage() {
	echo -e "Usage: $PROGNAME [-h|--help]"
}

help_message() {
  cat <<- _EOF_
  $PROGNAME ver. $VERSION
  Undeploy all stacks and remove all installed stack info.

  $(usage)

  Options:
  -h, --help  Display this help message and exit.

_EOF_
  return
}
##
## MAIN
##
# Trap signals
trap "signal_exit TERM" TERM HUP
trap "signal_exit INT"  INT


logger_init
log_script_entry "${PROGNAME}"
umask 002

# Parse command-line
while [[ -n $1 ]]; do
  case $1 in
    -h | --help)
      help_message; graceful_exit ;;
    -* | --*)
      usage
      logger_error_exit "Unknown option $1" ;;
    *)
      logger_debug "Argument $1 to process..." ;;
  esac
  shift
done

# Sanity checks
#Check_Runnable

if [[ $# -eq 0 ]]; then
  # Make sure we stop any running service by calling remove all stacks
  "${SCRIPTS_DIR}"/stop-lockss
  if kubectl_cmd get namespace "lockss" >/dev/null; then
    kubectl_lockss delete svc,deployments,pods,pvc,secrets,configmaps --all | logger_debug
  fi
  kubectl_cmd delete pv -l app=lockss | logger_debug
  logger_info ""
  logger_info "Successfully removed all running service and removed all installed data."
  logger_info "You will need to rerun configure-lockss and start-lockss to run again."
fi

graceful_exit
