#!/bin/bash
# ---------------------------------------------------------------------------
# upgrade-alpha1-solr - Update the solr files to latest lockss format.
#
# Copyright (c) 2000-2019, Board of Trustees of Leland Stanford Jr. University
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
# may be used to endorse or promote products derived from this software without
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# Usage: update-alpha-lockss [-h|--help]
#
# Revision history:
# 2019-04-18 version 1
# ---------------------------------------------------------------------------

_0=${0##*/}
VERSION="1.0"

##
## Relative paths
##
_0=$(basename "${0}")
_D0=$(dirname "${0}")

##
## Load _util
##

. "${_D0}/_util"
. "${_D0}/_util_solr"

##
## Definitions
##

# Directories
COMPOSE_DIR="$( cd "${_D0}/.." >/dev/null 2>&1 && pwd )"
echo "Setting Compose Dir: ${COMPOSE_DIR}"
CONFIG_DIR="${COMPOSE_DIR}/config"
UPDATES_PATH="${_D0}/upgrades"
SYSTEM_CONF_FILE="${CONFIG_DIR}/system.cfg"

# Files
SYSTEM_CONF_FILE="${CONFIG_DIR}/system.cfg"
SOLR_HOME_PATCH="${UPDATES_PATH}/solr-home.tar.gz"

SOLR_USER="8983:8983"

msg "Loading system configuration from ${SYSTEM_CONF_FILE}"
set -a
    . "${SYSTEM_CONF_FILE}"
set +a

if ! am_i_root ; then
  err_exit "this script must be run as root."
fi

echo "  ---------------------------  "
msg "${_0}: Checking solr home directory..."
SOLR_HOME_PATH="${LOCKSS_DATA_DIR}/lockss-stack-solr-data"
CORE_PATH="${SOLR_HOME_PATH}/mycores"

if [ -f "${SOLR_HOME_PATH}/solr.xml" -a -d "${CORE_PATH}/${LOCKSS_SOLR_CORE_REPO}"  ]; then
  msg "${_0}: Solr home has already been patched."
else
  msg "${_0}: Unpacking Solr home patch files to ${SOLR_HOME_PATH}."
  tar -xzf "${SOLR_HOME_PATCH}" -C "${SOLR_HOME_PATH}"
  # create the directory and move the lockss core repo.
  msg "${_0}: Creating default subdir ${CORE_PATH}"
  mkdir -p "${CORE_PATH}" ||
    err_exit "Unable to create directory ${CORE_PATH}"
  if [ -d "${SOLR_HOME_PATH}/${LOCKSS_SOLR_CORE_REPO}" ]; then
    msg "${_0}: Moving ${LOCKSS_SOLR_CORE_REPO} to default dir ${CORE_PATH}"
    mv "${SOLR_HOME_PATH}/${LOCKSS_SOLR_CORE_REPO}" "${CORE_PATH}" ||
      err_exit "Unable to move old repo from ${SOLR_HOME_PATH}/${LOCKSS_SOLR_CORE_REPO} to ${CORE_PATH}"
  fi
  echo "  ---------------------------  "
fi

msg "${_0}: Verifying and updating lockss solr core..."
verify_and_update_lockss_core "${LOCKSS_SOLR_CORE_REPO}" "${SOLR_HOME_PATH}" ||
  err_exit "Attempt to verify and update the LOCKSS Solr core failed!"
msg "${_0}: Fixing file permissions..."
chown -R "${SOLR_USER}" "${SOLR_HOME_PATH}" ||
  err_exit "Attempt to change ownership to ${SOLR_USER} on ${SOLR_HOME_PATH} failed."
