#!/bin/bash
# ---------------------------------------------------------------------------
# upgrade-to-alpha6 -
#
# Copyright (c) 2000-2022, Board of Trustees of Leland Stanford Jr. University
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
# may be used to endorse or promote products derived from this software without
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# Usage: upgrade-to-alpha6 [-h|--help]
#
# Revision history:
# 2022-09-22 version 1
# ---------------------------------------------------------------------------

PROGNAME=${0##*/}
VERSION="1.0"

UPGRADE_FROM="2\.0(?:\.(\d))?-alpha6.?"
UPGRADE_TO="2.0.60-alpha6"

## Relative paths
##

_0=$(basename "${0}")
_D0=$(dirname "${0}")

##
## Load _util
##

. "${_D0}/../_util"

COMPOSE_DIR="$(cd "${_D0}/../.." >/dev/null 2>&1 && pwd)"
CONFIG_DIR="${COMPOSE_DIR}/config"
SCRIPTS_DIR="${COMPOSE_DIR}/scripts"
LIB_DIR="${SCRIPTS_DIR}/lib"
UPDATES_DIR="${SCRIPTS_DIR}/upgrades"
DOCKER_CONFIGS_DIR="${CONFIG_DIR}/configs"
TEMPLATES_DIR="${CONFIG_DIR}/templates"
USEROPTS_DIR="${CONFIG_DIR}/useropts"

##
## Definitions
##
declare -a arr svcs
declare -a arr lockss_owned
STACK_PREFIX="lockss-stack"
SYSTEM_CONF_FILE="${CONFIG_DIR}/system.cfg"
set -a
. "${SYSTEM_CONF_FILE}"
set +a

clean_up() { # Perform pre-exit housekeeping
	return
}

error_exit() {
	echo -e "${PROGNAME}: ${1:-"Unknown Error"}" >&2
	clean_up
	exit 1
}

graceful_exit() {
	clean_up
	exit
}

signal_exit() { # Handle trapped signals
	case $1 in
		INT)
			error_exit "Program interrupted by user" ;;
		TERM)
			echo -e "\n$PROGNAME: Program terminated" >&2
			graceful_exit ;;
		*)
			error_exit "$PROGNAME: Terminating on unknown signal" ;;
	esac
}

usage() {
	echo -e "Usage: $PROGNAME [-h|--help]"
}

help_message() {
  cat <<- _EOF_
  $PROGNAME ver. $VERSION
  Update alpha6 from a previous alpha release.

  $(usage)

  Options:
  -h, --help  Display this help message and exit.

_EOF_
  return
}

nuke_journal_files() {
  IFS=';' read -r -a repoPaths <<< "${LOCKSS_REPO_HOST_DIRS}"
  for dir in "${repoPaths[@]}"; do
    if [ ! -z "${dir}" ]; then
      find "${dir}/${STACK_PREFIX}-repo-content" -type f -name "lockss-repo.warc" -delete 2> /dev/null
    fi
  done
}

move_tmp_warcs() {
  IFS=';' read -r -a repoPaths <<< "${LOCKSS_REPO_HOST_DIRS}"
  for dir in "${repoPaths[@]}"; do
    TEMPWARCS_DIR="${dir}/${STACK_PREFIX}-repo-content/tempwarcs"
    TMP_DIR="${dir}/${STACK_PREFIX}-repo-content/tmp"
    if [ -d "${TEMPWARCS_DIR}" ]; then
      mkdir -p "${TMP_DIR}"
      mv "${TEMPWARCS_DIR}" "${TMP_DIR}/warcs"
    fi
  done
}

rename_collections() {
  IFS=';' read -r -a repoPaths <<< "${LOCKSS_REPO_HOST_DIRS}"
  for dir in "${repoPaths[@]}"; do
    COLLECTIONS_DIR="${dir}/${STACK_PREFIX}-repo-content/collections"
    NAMESPACES_DIR="${dir}/${STACK_PREFIX}-repo-content/ns"
    if [ -d "${COLLECTIONS_DIR}" ]; then
      mv "${COLLECTIONS_DIR}" "${NAMESPACES_DIR}"
    fi
  done
}

reset_repo_index_state() {
  IFS=';' read -r -a repoPaths <<< "${LOCKSS_REPO_HOST_DIRS}"
  for dir in "${repoPaths[@]}"; do
    INDEX_STATE_DIR="${dir}/${STACK_PREFIX}-repo-data/state/index"
    if [ -d "${INDEX_STATE_DIR}" ]; then
      logger_info "Removing files from ${INDEX_STATE_DIR}"
      rm -f "${INDEX_STATE_DIR}"/reindex*
      rm -f "${INDEX_STATE_DIR}"/solr/*
    fi
  done
}

update_solr_index() {
  local SOLR_HOME_PATH="${LOCKSS_DATA_DIR}/${STACK_PREFIX}-solr-data"

  if [ -d "${SOLR_HOME_PATH}" ]; then
    tar czf ${SOLR_HOME_PATH}."`date +%Y%m%d%H%M`.tar.gz" "${SOLR_HOME_PATH}"
    rm -rf "${SOLR_HOME_PATH}"
  fi

  reset_repo_index_state

  # Signal to the repository service that a reindex is needed
  signal_reindex ${STACK_PREFIX}
}

###
## MAIN
###
# Trap signals
trap "signal_exit TERM" TERM HUP
trap "signal_exit INT"  INT
# Source system config file

if [ ! -r "$SYSTEM_CONF_FILE" ]; then
  err "$_0: The system configuration file does not exist.  This script requires the ./config/system.cfg file."
  err_exit "$_0: Run scripts/configure-lockss first."
fi

# Parse command-line
while [[ $# -gt 0 ]]; do
  case $1 in
    -h | --help)
      help_message; graceful_exit ;;
    -* | --*)
      usage
      error_exit "Unknown option $1" ;;
    *)
      shift
      ;;
  esac
done

# Sanity checks
Check_Runnable
Check_Stopped
Check_Configured

logger_init

read_config ${SYSTEM_CONF_FILE}
logger_debug "Loaded LOCKSS system configuration"

VERSION_FILE="${LOCKSS_DATA_DIR}/VERSION"

if [ ! -f "${VERSION_FILE}" ]; then
  error_exit "VERSION file not found in LOCKSS data directory; upgrade not necessary"
fi

CUR_VERSION="`cat ${VERSION_FILE}`"

if Parse_Lockss_Version "${CUR_VERSION}"; then
  case "${MATCH_MAJOR}.${MATCH_MINOR}-${MATCH_SUFFIX}" in
    2.0-alpha5)
      logger_info "Upgrade from alpha5"
      rename_collections
      move_tmp_warcs
      nuke_journal_files
      update_solr_index
      ;;
    2.0-alpha6)
      logger_info "Upgrade already applied (alpha6)"
      ;;
    *)
      error_exit "Do not know how to upgrade from ${CUR_VERSION}"
      ;;
  esac
else
  error_exit "Unexpected version: ${CUR_VERSION}"
fi

Set_Lockss_Version "${UPGRADE_TO}"
logger_info "Updated LOCKSS version file"

logger_info "Upgrade completed"
graceful_exit
