#!/usr/bin/env bash
#
# Copyright (c) 2000-2020, Board of Trustees of Leland Stanford Jr. University
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
# may be used to endorse or promote products derived from this software without
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#
PROGNAME=${0##*/}
VERSION="1.0"

##
## Relative paths
##

_0=$(basename "${0}")
_D0=$(dirname "${0}")

##
## Load _util
##

. "${_D0}/../_util"

COMPOSE_DIR="$(cd "${_D0}/../.." >/dev/null 2>&1 && pwd)"
CONFIG_DIR="${COMPOSE_DIR}/config"
SCRIPTS_DIR="${COMPOSE_DIR}/scripts"
LIB_DIR="${SCRIPTS_DIR}/lib"
UPDATES_DIR="${SCRIPTS_DIR}/upgrades"
DOCKER_CONFIGS_DIR="${CONFIG_DIR}/configs"
TEMPLATES_DIR="${CONFIG_DIR}/templates"

UPGRADE_ENV_TMPL="${CONFIG_DIR}/env.mustache.upgrade"
STACK_PREFIX="lockss-stack"

SYSTEM_CONF_FILE="${CONFIG_DIR}/system.cfg"
# Source system config file
source_config
STACK_PREFIX="lockss-stack"
POSTGRES_DATA_DIR="${LOCKSS_DATA_DIR}/${STACK_PREFIX}-postgres-data"
POSTGRES_DATA_DIR_BAK="${POSTGRES_DATA_DIR}.bak"

clean_up() { # Perform pre-exit housekeeping
  restore_env
  "${SCRIPTS_DIR}"/stop-lockss >/dev/null
  log_script_exit  "${PROGNAME}"
}

logger_error_exit() {
  logger_fatal "${1:-"Unknown Error"}" >&2
  clean_up
  exit 1
}

error_exit() {
  echo -e "${PROGNAME}: ${1:-"Unknown Error"}" >&2
  clean_up
  exit 1
}

graceful_exit() {
  clean_up
  exit
}

signal_exit() { # Handle trapped signals
  case $1 in
  INT)
    error_exit "Program interrupted by user"
    ;;
  TERM)
    echo -e "\n$PROGNAME: Program terminated" >&2
    graceful_exit
    ;;
  *)
    error_exit "$PROGNAME: Terminating on unknown signal"
    ;;
  esac
}

usage() {
  echo -e "Usage: $PROGNAME [-h|--help] [-o|--old-version]  [-n|--new-version] [-v]"
}

help_message() {
  cat <<-_EOF_
  $PROGNAME ver. $VERSION
  Upgrade the Postgres version.

  $(usage)

  Options:
  -h, --help  Display this help message and exit.
  -o, --old-version The version of the old postgres container.
  -n, --new-version The version of the new postgres container.
  -v, --verbose Use verbose output.

_EOF_
  return
}

restore_env() {
  if [ -f "${UPGRADE_ENV_TMPL}" ]; then
    rm -f "${UPGRADE_ENV_TMPL}" >/dev/null
  fi
}

check_versions() {
  if [ -z ${NEW_VERSION+x} ]; then
    NEW_VERSION=${POSTGRES_VERSION}
  fi
  if [ -z ${OLD_VERSION+x} ]; then
      logger_error_exit "Unable to determine old container version."
  fi
  version_compare $OLD_VERSION $NEW_VERSION
  case $? in
    0)
      logger_error_exit "The current version is identical to the upgrade version $NEW_VERSION."
      ;;
    1)
      logger_error_exit "The current version is newer than the upgrade version $NEW_VERSION."
      ;;
    2)
      logger_info "Upgrading postgres container from ${OLD_VERSION} to ${NEW_VERSION}."
      ;;
  esac
}

version_compare()
{
    if [[ $1 == $2 ]]; then
        return 0
    fi
    local IFS=.
    # Everything after the first character not in [^0-9.] is compared
    local i a=(${1%%[^0-9.]*}) b=(${2%%[^0-9.]*})
    local arem=${1#${1%%[^0-9.]*}} brem=${2#${2%%[^0-9.]*}}
    for ((i=0; i<${#a[@]} || i<${#b[@]}; i++)); do
        if ((10#${a[i]:-0} < 10#${b[i]:-0})); then
            return 2
        elif ((10#${a[i]:-0} > 10#${b[i]:-0})); then
            return 1
        fi
    done
    if [ "$arem" '<' "$brem" ]; then
        return 2
    elif [ "$arem" '>' "$brem" ]; then
        return 1
    fi
    return 0
}

dump_old_version()
{
  # add the postgres version to the opt file
  echo POSTGRES_VERSION=${OLD_VERSION} | tee "${UPGRADE_ENV_TMPL}"

  # bring up the old version
  "${SCRIPTS_DIR}"/start-lockss -s "postgres" || logger_error_exit "Attempt to start old postgres failed."
  podname="deploy/lockss-postgres-service"
  #wait for the  deployment to be marked as Available
  kubectl_lockss wait deployment lockss-postgres-service --for condition=Available=True --timeout=180s
  # dump the old versions content
  kubectl_lockss exec -it ${podname} -- pg_dumpall -c -U "${LOCKSS_POSTGRES_USER}" --file="/tmp/${DUMP_FILE}" ||
    logger_error_exit "Unable to exec into pod to perform database dump."
  # shutdown old version
  "${SCRIPTS_DIR}"/stop-lockss  || logger_error_exit "Attempt to stop postgres failed."
  logger_info "moving old postgres directory out of the way..."
  mv "${POSTGRES_DATA_DIR}" "${POSTGRES_DATA_DIR_BAK}" ||
    logger_error_exit "Unable to backup data dir: ${POSTGRES_DATA_DIR}"
  restore_env
}

restore_dump()
{
# bring up the new version -- psql -q -U
 "${SCRIPTS_DIR}"/start-lockss -s "postgres" || logger_error_exit "Attempt to start new postgres failed."
 kubectl_lockss wait deployment lockss-postgres-service --for condition=Available=True --timeout=180s
 # load the dump into the new version
 kubectl_lockss exec -it deploy/lockss-postgres-service -- psql -q -U "${LOCKSS_POSTGRES_USER}" --file="/tmp/${DUMP_FILE}" postgres ||
   logger_error_exit "Unable to exec into pod to perform database restore."
 # shutdown the new version.
 "${SCRIPTS_DIR}"/stop-lockss || logger_error_exit "Attempt to stop running postgres failed."
}

###
## MAIN
###
# Trap signals 1233  sudo rm -rf /lockss/lockss-stack-postgres-data

trap "signal_exit TERM" TERM HUP
trap "signal_exit INT"  INT

# Parse command-line
while [[ $# -gt 0 ]]; do
  case $1 in
    -h | --help)
      help_message; graceful_exit ;;
    -n | --new-version)
      NEW_VERSION="$2"
      shift; shift
      ;;
    -o | --old-version)
      OLD_VERSION="$2"
      shift; shift
      ;;
    -v | --verbose)
      VERBOSE="--verbose"
      ;;
    -* | --*)
      usage
      error_exit "Unknown option $1" ;;
    *)
      shift
      ;;
  esac
done

# Sanity checks
Check_Runnable
Check_Configured

logger_init
check_versions
DUMP_FILE="${OLD_VERSION}.dump"
dump_old_version
restore_dump

logger_info "Postgres upgrade completed."

graceful_exit
